insert into client_statistics.client_sql_statements (name, statement) values
('ActiveSync - devices - Details',
'select \nAPPLICATION as Device,\ncount(APPLICATION) as Count,\n(Count(APPLICATION)* 100 / (Select Count(*) From Clients where CLIENT_NAME like \"ActiveSync%\")) as Percentage\nfrom Clients \nwhere CLIENT_NAME like \"ActiveSync%\"\ngroup by APPLICATION\norder by Count desc'), 
('ActiveSync - versions',
'select CLIENT_NAME as Client, \ncount(CLIENT_NAME) as Count,\n(count(CLIENT_NAME) *100 / (select count(*) from Clients where CLIENT_NAME like \"ActiveSync%\")) as Percentage\nfrom Clients \nwhere CLIENT_NAME like \"ActiveSync%\"\ngroup by CLIENT_NAME\norder by Count desc'),
('All clients',
'select CLIENT_NAME as Client, \ncount(CLIENT_NAME) as Count, \n(Count(CLIENT_NAME)* 100 / (Select Count(*) From Clients)) as Percentage\nfrom Clients group by CLIENT_NAME\norder by Count desc'),
('All clients - without KerioAPI',
'select CLIENT_NAME as Client, \ncount(CLIENT_NAME) as Count\nfrom Clients \nwhere CLIENT_NAME <> \"Public API\"\ngroup by CLIENT_NAME\norder by Count desc'),
('Blackberry Connector - BES installation count',
'select CLIENT_NAME as Client,\nAPPLICATION_BINARY as Version,\nREMINDER_ID as InstallationID\nfrom Clients \nwhere CLIENT_NAME like \"KBC\"\ngroup by REMINDER_ID'),
('Blackberry Connector - BES version',
'select CLIENT_NAME as Client,\nAPPLICATION_BINARY as Version, \ncount(DISTINCT REMINDER_ID) as NumberOfInstallations\nfrom Clients \nwhere CLIENT_NAME like \"KBC\"\ngroup by APPLICATION_BINARY\norder by NumberOfInstallations desc'),
('Blackberry Connector - client OS',
'select CLIENT_NAME as Client,\nCLIENT_OS as Version, \ncount(DISTINCT REMINDER_ID,USER_ID) as Count\nfrom Clients \nwhere CLIENT_NAME like \"KBC\"\ngroup by CLIENT_OS\norder by Count desc'),
('Blackberry Connector - devices',
'select CLIENT_NAME as Client,\nAPPLICATION as Version, \ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME like \"KBC\"\ngroup by APPLICATION\norder by Count desc'),
('CalDAV - all clients',
'select CLIENT_NAME as Client,\nAPPLICATION as Version, \ncount(APPLICATION) as Count\nfrom Clients \nwhere (CLIENT_NAME like \"CalDAV\" or APPLICATION like \"% iCal%\" or APPLICATION like \"% Calendar%\" or APPLICATION like \"% dataaccessd%\") and CLIENT_NAME not like \"EWS\"\ngroup by APPLICATION\norder by Count desc'),
('CalDAV - clients',
'select CLIENT_NAME as Client,\nAPPLICATION as Version, \ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME like \"CalDAV\"\ngroup by APPLICATION\norder by Count desc'),
('CardDAV - all clients',
'select CLIENT_NAME as Client,\nAPPLICATION as Version, \ncount(APPLICATION) as Count\nfrom Clients \nwhere (CLIENT_NAME like \"CardDAV\" or APPLICATION like \"% CardDAVPlugin%\" or APPLICATION like \"% Contacts%\" or APPLICATION like \"% AddressBook%\") and CLIENT_NAME not like \"EWS\"\ngroup by APPLICATION\norder by Count desc'),
('CardDAV - clients',
'select CLIENT_NAME as Client,\nAPPLICATION as Version, \ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME like \"CardDAV\"\ngroup by APPLICATION\norder by Count desc'),
('EWS - clients',
'select CLIENT_NAME as Client,\nAPPLICATION as Version, \ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME like \"EWS\"\ngroup by APPLICATION\norder by Count desc'),
('KOFF - clients',
'select CLIENT_NAME as Client,\nAPPLICATION as Version, \ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME like \"KOFF\"\ngroup by APPLICATION\norder by Count desc'),
('KSC - clients by OS',
'select CLIENT_OS as \"Client OS\",\ncount(*) as Count\nfrom Clients \nwhere APPLICATION like \"KSC%\"\ngroup by CLIENT_OS\norder by Count desc'),
('KSC - clients by version',
'select APPLICATION as Client,\ncount(*) as Count\nfrom Clients \nwhere APPLICATION like \"KSC%\"\ngroup by APPLICATION\norder by Count desc'),
('Public API - clients',
'select CLIENT_NAME as Protocol,\nAPPLICATION as \"Public API client\",\ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME=\"Public API\"\ngroup by APPLICATION\norder by Count desc'),
('Public API - WAM top functions',
'select APPLICATION as \"Public API client\",APPLICATION_BINARY as Function,\ncount(APPLICATION_BINARY) as Count\nfrom Clients \nwhere CLIENT_NAME=\"Public API\" and APPLICATION=\"Kerio\/WAM\"\ngroup by APPLICATION_BINARY\norder by Count desc'),
('Public API - WM2 top functions',
'select APPLICATION as \"Public API client\",APPLICATION_BINARY as Function,\ncount(APPLICATION_BINARY) as Count\nfrom Clients \nwhere CLIENT_NAME=\"Public API\" and APPLICATION=\"Kerio\/WebMail\"\ngroup by APPLICATION_BINARY\norder by Count desc'),
('WebAdmin browsers',
'select CLIENT_NAME as Client,\nAPPLICATION as Browser, \ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME = \"WebAdmin\"\ngroup by APPLICATION\nhaving Count > 10\norder by Count desc'),
('WebAdmin browsers Chrome',
'select CLIENT_NAME as Client,\nAPPLICATION as Browser, \ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME = \"WebAdmin\" and APPLICATION like \"Chrome%\"\ngroup by APPLICATION\nhaving Count > 10\norder by Count desc'),
('WebAdmin browsers Firefox',
'select CLIENT_NAME as Client,\nAPPLICATION as Browser, \ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME = \"WebAdmin\" and APPLICATION like \"Firefox%\"\ngroup by APPLICATION\nhaving Count > 10\norder by Count desc'),
('WebAdmin browsers MSIE',
'select CLIENT_NAME as Client,\nAPPLICATION as Browser, \ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME = \"WebAdmin\" and APPLICATION like \"MSIE%\"\ngroup by APPLICATION\nhaving Count > 10\norder by Count desc'),
('WebAdmin browsers Safari',
'select CLIENT_NAME as Client,\nAPPLICATION as Browser, \ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME = \"WebAdmin\" and APPLICATION like \"Safari%\"\ngroup by APPLICATION\nhaving Count > 10\norder by Count desc'),
('WebDAV - Entourage versions',
'select CLIENT_NAME as Client,\nAPPLICATION as Version, \ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME like \"WebDAV\" and APPLICATION like \"Entourage%\"\ngroup by APPLICATION\norder by Count desc'),
('WebMail2 browsers',
'select CLIENT_NAME as Client,\nAPPLICATION as Browser, \ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME = \"WebMail2\"\ngroup by APPLICATION\nhaving Count > 10\norder by Count desc'),
('WebMail2 browsers - Chrome',
'select CLIENT_NAME as Client,\nAPPLICATION as Browser, \ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME = \"WebMail2\" and APPLICATION like \"Chrome%\"\ngroup by Browser\norder by Count desc'),
('WebMail2 browsers - Firefox',
'select CLIENT_NAME as Client,\nAPPLICATION as Browser, \ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME = \"WebMail2\" and APPLICATION like \"Firefox%\"\ngroup by Browser\norder by Count desc'),
('WebMail2 browsers - MSIE',
'select CLIENT_NAME as Client,\nAPPLICATION as Browser, \ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME = \"WebMail2\" and APPLICATION like \"MSIE%\"\ngroup by Browser\norder by Count desc'),
('WebMail2 browsers - Safari',
'select CLIENT_NAME as Client,\nAPPLICATION as Browser, \ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME = \"WebMail2\" and APPLICATION like \"Safari%\"\ngroup by Browser\norder by Count desc'),
('WebMail browsers',
'select CLIENT_NAME as Client,\nAPPLICATION as Browser, \ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME = \"WebMail\"\ngroup by APPLICATION\nhaving Count > 10\norder by Count desc'),
('WebMail browsers - Chrome',
'select CLIENT_NAME as Client,\nAPPLICATION as Browser, \ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME = \"WebMail\" and APPLICATION like \"Chrome%\"\ngroup by Browser\norder by Count desc'),
('WebMail browsers - Firefox',
'select CLIENT_NAME as Client,\nAPPLICATION as Browser, \ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME = \"WebMail\" and APPLICATION like \"Firefox%\"\ngroup by Browser\norder by Count desc'),
('WebMail browsers - MSIE',
'select CLIENT_NAME as Client,\nAPPLICATION as Browser, \ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME = \"WebMail\" and APPLICATION like \"MSIE%\"\ngroup by Browser\norder by Count desc'),
('WebMail browsers - Safari',
'select CLIENT_NAME as Client,\nAPPLICATION as Browser, \ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME = \"WebMail\" and APPLICATION like \"Safari%\"\ngroup by Browser\norder by Count desc'),
('WebMail Mini browsers',
'select CLIENT_NAME as Client,\nAPPLICATION as Browser, \ncount(APPLICATION) as Count\nfrom Clients \nwhere CLIENT_NAME like \"WebMail Mini\"\ngroup by APPLICATION\nhaving Count > 10\norder by Count desc'),
('XMPP - installations',
'select CLIENT_NAME as Client,\nREMINDER_ID as InstallationID,\ncount(USER_ID) as NumberOfUsers\nfrom Clients \nwhere CLIENT_NAME like \"XMPP\"\ngroup by REMINDER_ID\norder by NumberOfUsers desc')
